name: novel
description: Develop your own visual novels easily.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bordered_text: ^2.0.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  just_audio_mpv: ^0.1.4
  just_audio_windows: ^0.1.0
  just_audio: ^0.9.28
  mutex: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
