name: novel
description: Develop your own visual novels easily.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^1.0.1
  bordered_text: ^2.0.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  mutex: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
